import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: 'https://quotinghub.co.za', changeFrequency: 'monthly', priority: 1 },
    { url: 'https://quotinghub.co.za/pricing', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-cape-town', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-johannesburg', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-durban', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-pretoria', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-port-elizabeth', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-stellenbosch', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-george', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-bloemfontein', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/interior-design-software-east-london', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/trades', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/trades/electrician', changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://quotinghub.co.za/faq', changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://quotinghub.co.za/blog', changeFrequency: 'weekly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/how-to-write-interior-design-quotation-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/interior-design-fee-structure-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/interior-design-quotation-template-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/interior-designer-vs-interior-decorator-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/vat-on-interior-design-services-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/best-interior-design-software-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/why-spreadsheets-are-costing-your-interior-design-studio', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/purchase-orders-for-interior-designers-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/how-to-start-interior-design-business-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/programa-vs-quotinghub-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/quotinghub-for-south-african-interior-designers', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/houzz-pro-vs-quotinghub-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/designfiles-vs-quotinghub-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/programa-alternatives-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/how-to-invoice-clients-interior-design-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/interior-design-invoice-template-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/interior-design-contract-template-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/how-to-open-trade-accounts-with-sa-furniture-suppliers', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/best-fabric-and-furniture-suppliers-for-interior-designers-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/how-to-manage-supplier-lead-times-south-africa', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/south-african-interior-design-industry-statistics-2026', changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://quotinghub.co.za/blog/interior-design-courses-south-africa', changeFrequency: 'monthly', priority: 0.8 },
  ]
}
